import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Nav from '../components/Nav'
import { signIn } from 'next-auth/react'
export default function Home() {
  const {data:session}=useSession()
  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <Nav/>

      {session?.user ? (
        <>
        <h1>true</h1>
        </>
      ): (
        <>
        you are not authenticated
        <button onClick={()=>{signIn()}} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Login</button>
        </>
      )}

      
    </>
  )
}
